server:
  port:8080
name: 我是张三
age: 22
student:
  name: 李四
  age: 20
  
logging:
  path: /user/local/log
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: ERROR

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
